const STATES = {
    INITIAL: 0,
    VEHICLE_SELECTION: 1,
    REPORT_TYPE_SELECTION: 2,
    REPORT_DETAILS: 3,
    MORE_DETAILS: 4,
    ANSWER_MEDIA: 5,
    MEDIA_UPLOAD: 6,
    LOCATION_SELECTION: 7,
    FINAL: 8,
};

module.exports = STATES;
